export var hedges = [
  "a bit",
  "about",
  "actually",
  "allege",
  "alleged",
  "almost",
  "almost never",
  "always",
  "and all that",
  "and so forth",
  "apparent",
  "apparently",
  "appear",
  "appear to be",
  "appeared",
  "appears",
  "approximately",
  "around",
  "assume",
  "assumed",
  "assumes",
  "assumption",
  "at least",
  "basically",
  "be sure",
  "believe",
  "believed",
  "believes",
  "bunch",
  "can",
  "certain",
  "certainly",
  "clear",
  "clearly",
  "conceivably",
  "consider",
  "considered",
  "considers",
  "consistent with",
  "could",
  "couple",
  "definite",
  "definitely",
  "diagnostic",
  "don't know",
  "doubt",
  "doubtful",
  "effectively",
  "estimate",
  "estimated",
  "estimates",
  "et cetera",
  "evidently",
  "fairly",
  "few",
  "find",
  "finds",
  "found",
  "frequently",
  "generally",
  "guess",
  "guessed",
  "guesses",
  "hopefully",
  "if i'm understanding you correctly",
  "improbable",
  "in general",
  "in my mind",
  "in my opinion",
  "in my understanding",
  "in my view",
  "inconclusive",
  "indicate",
  "kind of",
  "largely",
  "like",
  "likely",
  "little",
  "look like",
  "looks like",
  "mainly",
  "many",
  "may",
  "maybe",
  "might",
  "more or less",
  "most",
  "mostly",
  "much",
  "must",
  "my impression",
  "my thinking is",
  "my understanding is",
  "necessarily",
  "occasionally",
  "often",
  "overall",
  "partially",
  "perhaps",
  "possibility",
  "possible",
  "possibly",
  "practically",
  "presumable",
  "presumably",
  "pretty",
  "probability",
  "probable",
  "probably",
  "quite",
  "quite clearly",
  "rare",
  "rarely",
  "rather",
  "read",
  "really",
  "roughly",
  "say",
  "says",
  "seem",
  "seemed",
  "seems",
  "seldom",
  "several",
  "should",
  "so far",
  "some",
  "somebody",
  "somehow",
  "someone",
  "something",
  "something or other",
  "sometimes",
  "somewhat",
  "somewhere",
  "sort of",
  "speculate",
  "speculated",
  "speculates",
  "suggest",
  "suggested",
  "suggestive",
  "suggests",
  "suppose",
  "supposed",
  "supposedly",
  "supposes",
  "surely",
  "tend",
  "their impression",
  "think",
  "thinks",
  "thought",
  "understand",
  "understands",
  "understood",
  "unlikely",
  "unsure",
  "usually",
  "virtually",
  "will",
  "would",
  "можно",
  "безусловно",
  "более менее",
  "будут",
  "бы",
  "быть уверенным",
  "в моей голове",
  "в моем понимании",
  "в некотором роде",
  "в общем",
  "в основном",
  "в принципе",
  "в самом деле",
  "в соответствии с",
  "в целом",
  "верил",
  "верит",
  "вероятно",
  "вероятность",
  "вероятный",
  "весьма",
  "во многом",
  "возможно",
  "возможность",
  "возможный",
  "время от времени",
  "вроде, как бы, что-то вроде",
  "вряд ли",
  "всегда",
  "выглядит как",
  "где-то",
  "говорит",
  "грубо",
  "диагностика",
  "довольно",
  "довольно часто",
  "догадки",
  "должен",
  "думает",
  "если я правильно тебя понимаю",
  "и все такое",
  "и так далее",
  "иметь тенденцию",
  "иногда",
  "их впечатление",
  "кажется",
  "казалось",
  "казаться",
  "как",
  "как минимум",
  "как-то",
  "конечно",
  "кто то",
  "кто-то",
  "маленький",
  "много",
  "мог",
  "мое впечатление",
  "мое мышление",
  "мое понимание",
  "может быть",
  "мочь",
  "мысль",
  "наводящий на размышления",
  "найденный",
  "найти",
  "находит",
  "не знаю",
  "невероятный",
  "немного",
  "несколько",
  "неубедительный",
  "неуверенный",
  "общий",
  "обычно",
  "обязательно",
  "оказаться",
  "около",
  "определенно",
  "определенный",
  "оцененный",
  "оценивать",
  "оценки",
  "очевидно",
  "очевидный",
  "пара",
  "по всей видимости",
  "полагать",
  "понимает",
  "понял",
  "понять",
  "похоже",
  "почти",
  "почти никогда",
  "появился",
  "появляется",
  "появляться",
  "практически",
  "предлагает",
  "предложенный",
  "предложить",
  "предполагаемый",
  "предполагает",
  "предполагать",
  "предположение",
  "предположил",
  "предположительно",
  "примерно",
  "рассмотреть возможность",
  "редкий",
  "редко",
  "с моей точки зрения",
  "с надеждой",
  "самый",
  "связка",
  "сказать",
  "скорее",
  "совершенно ясно",
  "сомневаться",
  "сомнительный",
  "спекулировать",
  "считает",
  "считается",
  "считать",
  "угадал",
  "уже",
  "указывать",
  "утверждать",
  "фактически",
  "частично",
  "часто",
  "четко",
  "читать",
  "что-нибудь",
  "что-то вроде",
  "что-то или другое",
  "эффективно",
  "я считаю",
  "ясно"
]
